# Generated by Django 5.0.4 on 2024-05-08 09:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status_valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_valid_to', models.DateTimeField(blank=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
