# Generated by Django 5.0.4 on 2024-05-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0002_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status_valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
