# Generated by Django 5.0.4 on 2024-05-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0004_account_guid_alter_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='guid',
            new_name='account_guid',
        ),
    ]
