# Generated by Django 5.0.4 on 2024-06-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0006_account_base_currency_alter_account_status_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='base_currency',
            field=models.CharField(max_length=3),
        ),
    ]
