# Generated by Django 5.0.4 on 2024-06-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0007_alter_account_base_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='base_currency',
            new_name='currency',
        ),
    ]
