# Generated by Django 5.0.4 on 2024-05-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='transaction_date',
        ),
    ]
