# Generated by Django 5.0.4 on 2024-05-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_api', '0003_transaction_transaction_guid_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('CLEARED', 'Cleared'), ('UNCLEARED', 'Uncleared')], default='UNCLEARED', max_length=9),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], default='CREDIT', max_length=6),
        ),
    ]
